# Generated by Django 5.0.6 on 2024-05-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('type', models.CharField(choices=[('mammal', 'Млекопитающее'), ('fish', 'Рыба'), ('reptile', 'Рептилия'), ('birds', 'Пернатые')], default='mammal', max_length=100, verbose_name='Род')),
                ('information', models.TextField(blank=True, verbose_name='Информация')),
                ('population', models.PositiveIntegerField(default=0, verbose_name='Популяция')),
                ('is_rare', models.BooleanField(default=False, verbose_name='Вымерающие животные')),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животные',
            },
        ),
    ]
