# Generated by Django 5.0.6 on 2024-05-25 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
            },
        ),
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.DateField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Аватар')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Заработная плата')),
                ('is_teamlead', models.BooleanField(default=False, verbose_name='Тимлид')),
                ('drade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmers', to='core.grade', verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Программист',
                'verbose_name_plural': 'Программисты',
                'ordering': ('surname', 'name', 'patronymic'),
            },
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
    ]
