# Generated by Django 5.0.6 on 2024-05-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_grade_programmer_delete_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmer',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
    ]
